// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrnJaLXqbAnvhZOXLydrgX6R5WOyBNGNM',
    appId: '1:132866671898:web:8ca6d006b31c1f7e8558a3',
    messagingSenderId: '132866671898',
    projectId: 'nilico-c8f58',
    authDomain: 'nilico-c8f58.firebaseapp.com',
    storageBucket: 'nilico-c8f58.firebasestorage.app',
    measurementId: 'G-ZP5QJVLX95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-0HoZQiemVXskJ3LG5W6YxGqWATF7rxY',
    appId: '1:132866671898:android:bbabc619342965e68558a3',
    messagingSenderId: '132866671898',
    projectId: 'nilico-c8f58',
    storageBucket: 'nilico-c8f58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUfm-jVAXlOYe7fNFYCfATPZaP3vIiiIU',
    appId: '1:132866671898:ios:0cbc040d67785d6f8558a3',
    messagingSenderId: '132866671898',
    projectId: 'nilico-c8f58',
    storageBucket: 'nilico-c8f58.firebasestorage.app',
    iosBundleId: 'com.nilico.babytracker',
  );
}
